name: SpawnArrows
version: ${project.version}
main: com.drafakiller.spawnarrows.SpawnArrows
api-version: 1.16
authors: [ DrafaKiller ]
description: Craft arrows using mob drops and shot them to spawn them anywhere u want, interesting and fun against other players.
website: drafakiller.com
